### ISSUE TITLE
Using xidel to extract non-ASCII text ?

### ISSUE THREAD

**Issue by Baltazar500** [benibela/xidel#109]
"extract" with regular expressions (.*) extracts only ASCII text from html, skipping non-ASCII text. If I use curl + iconv and xidel on stdout there is no problem with processing. The input-encoding option is required (remote server encoding), output-encoding/stdin-encoding does not help

**Comment by benibela** [comment]
It assumes UTF-8 text

When the input comes from a server, it should automatically be converted 
to UTF-8 from the encoding in the HTTP  headers

**Comment by Baltazar500** [comment]
>When the input comes from a server, it should automatically be converted
to UTF-8 from the encoding in the HTTP  headers

It’s the same story with a locally downloaded htm file.

this does not work

```
xidel -se 'json(extract(extract($raw, "var playerParams = \{.*\};"), "\{.*\}")).params()' ./vk.tmp

cat ./vk.tmp|xidel --stdin-encoding=cp1251 -se 'json(extract(extract($raw, "var playerParams = \{.*\};"), "\{.*\}")).params()'
```

it works

```
iconv -f cp1251 ./vk.tmp|xidel -se 'json(extract(extract($raw, "var playerParams = \{.*\};"), "\{.*\}")).params()'

```
[vk.tmp.zip](https://github.com/benibela/xidel/files/12785514/vk.tmp.zip)

**Comment by Reino17** [comment]
Please update your old Xidel binary! We're at [0.9.9.8842](https://sourceforge.net/projects/videlibri/files/Xidel/Xidel%20development/) at the moment.

What you're looking for ultimately is probably...
```
xidel -s vk.tmp -e 'parse-json(//script/extract(.,"var playerParams = (.+);",1)).params()'
```
- `json()` has been replaced by [`parse-json()`](https://www.benibela.de/documentation/internettools/xpath-functions.html#jn-parse-json) and [`json-doc()`](https://www.benibela.de/documentation/internettools/xpath-functions.html#jn-json-doc).
- You're first of all parsing an HTML-source, so I suggest you use `//script` instead of `$raw`.
- No need for two `extract()` functions. One instance can extract the JSON-text no problem.

> ```
> iconv -f cp1251 ./vk.tmp|xidel ...
> ```
If I convert _'vk.tmp'_ to utf-8 (including `<meta content="charset=utf-8">`), then...
```
xidel -s vk_utf8.tmp -e 'parse-json(extract($raw,"var playerParams = (.+);",1)).params()'
```
...using `extract()` with `$raw` works fine, but this doesn't work with the windows-1251 _'vk.tmp'_. Maybe Benito could tell us why that is. But like I said; better to use `//script` instead of `$raw` anyway.

You could however use 2 instances of Xidel if you really want to use `$raw`:
```
xidel -s vk.tmp -e . --output-format=html | \
xidel -se 'parse-json(extract($raw,"var playerParams= (.+);",1)).params()'
```
...which is essentially:
```
xidel -s vk.tmp -e . --output-format=html --output-encoding="utf-8" | \
xidel -s --stdin-encoding="utf-8" -e 'parse-json(extract($raw,"var playerParams= (.+);",1)).params()'
```

**Comment by benibela** [comment]
>      <meta http-equiv="content-type" content="text/html; charset=windows-1251" />

Xidel does not support charset windows-1251 on Linux

I have implemented only windows-1252 (latin1)


But it can be compiled with `uses cwstring` in xidel.pas, then it calls libc/iconv to handle unknown charsets

**Comment by Baltazar500** [comment]
>But it can be compiled with uses cwstring in xidel.pas, then it calls libc/iconv to handle unknown charsets

I don't know much about compilation. Can you build a binary with support for unknown charsets ?

**Comment by Reino17** [comment]
Please pick your binary [here](https://nightly.link/benibela/xidel/workflows/main/master). Judging by the modified/creation datetime it should include this latest commit.

**Comment by Baltazar500** [comment]
@Reino17, Same story. Does not work. Need a pipe with iconv :(

**Comment by benibela** [comment]
apparently stdin-encoding is ignored for $raw  and pipes

but the html parser looks at the encoding:

    xidel vk.tmp -se 'json(extract(extract((//script[contains(., "playerParams")])[1], "var playerParams = \{.*\};"), "\{.*\}")).params()'

**Comment by Baltazar500** [comment]
@benibela, OK. Thank you. This works, including on early releases.
