### ISSUE TITLE
XPath bug

### ISSUE THREAD

**Issue by kjhughes** [benibela/xidel#27]
On the [demo website](http://videlibri.sourceforge.net/cgi-bin/xidelcgi?&data=%3Ctag%20id%3D%22r%22%3E%0A%20%20%3Ctag%20id%3D%22a%22%3Evalue%3C%2Ftag%3E%0A%20%20%3Ctag%20id%3D%22b%22%3Eval%3Cbr%2F%3Eue%3C%2Ftag%3E%0A%20%20%3Ctag%20id%3D%22c%22%3E%3Cspan%3Eval%3C%2Fspan%3E%3Cspan%3Eue%3C%2Fspan%3E%3C%2Ftag%3E%0A%20%20%3Ctag%20id%3D%22f%22%3E%20value%3C%2Ftag%3E%0A%20%20%3Ctag%20id%3D%22g%22%3EValue%3C%2Ftag%3E%0A%3C%2Ftag%3E&=&extract=%2F%2Ftag%5B.%3D%22value%22%5D&=&input-format=auto&printed-node-format=xml&output-format=adhoc&compatibility=Enable%20all%20extensions&dot-notation=unambiguous&extract-kind=auto), for this XML,

```
<tag id="r">
  <tag id="a">value</tag>
  <tag id="b">val<br/>ue</tag>
  <tag id="c"><span>val</span><span>ue</span></tag>
  <tag id="f"> value</tag>
  <tag id="g">Value</tag>
</tag>
```

this XPath, `//tag[.="value"]`, selects these nodes,

```
<tag id="a">value</tag>
<tag id="b">val<br/>ue</tag>
<tag id="c"><span>val</span><span>ue</span></tag>
<tag id="f"> value</tag>
<tag id="g">Value</tag>
```

but _**should**_ select these nodes:

```
<tag id="a">value</tag>
<tag id="b">val<br/>ue</tag>
<tag id="c"><span>val</span><span>ue</span></tag>
```

**Comment by kjhughes** [comment]
If you wish to claim that your tool supports XPath, then adherence to the standard trumps such legacy concerns regarding previous versions of your tool.  Conformance is everything in standards.   To intentionally chose non-conformance would undermine the credibility of your tool.  I know I wouldn't use or recommend a non-conformant XPath processor.

**Comment by benibela** [comment]
The standard is flexible, it actually allows one to have uncommon [string comparisons](https://www.w3.org/TR/xpath-functions-3/#string-compare).  E.g. the query could also return `<tag>walue</tag>` on a Swedish system.

**Comment by kjhughes** [comment]
Collations are not in play here, and _**nothing**_ in that section supports `//tag[.="value"]` selecting 

```
<tag id="f"> value</tag>
<tag id="g">Value</tag>
```

Without fixing this, your implementation is non-conformant.

**Comment by benibela** [comment]
`=` compares strings using the default collation.

But what exactly is the default collation? The XPath standard never defines it properly. The only place where it says anything specific about the default collation is that section, where it says the codepoint collation is used as fallback, if neither the user nor the system have specified a collation. Hence xidel as system chooses  a case-insensitive default collation. If the user would choose a whitespace normalizing case-insensitive collation, the current behavior is totally conformant. 

But I have now disabled the default whitespace ignoring, since it was also removing whitespace outside of comparisons to  see if someone will now complain about the change. I at least have gotten 193 failing test cases from it.

**Comment by kjhughes** [comment]
I do not see why you'd say that the XPath standard never defines the default collation properly...

[5.3.1 Collations](https://www.w3.org/TR/xpath-functions-3/#collations)

> If the default collation is not specified by the user or the system, the default collation is the [·Unicode codepoint collation·](https://www.w3.org/TR/xpath-functions-3/#dt-codepoint-collation).

And then:

[5.3.2 The Unicode Codepoint Collation
](https://www.w3.org/TR/xpath-functions-3/#codepoint-collation)
> The Unicode codepoint collation does not perform any normalization on the supplied strings.

It then goes on to specify the details of the default comparison.  There is no normalization.

Moreover, to implement a default collation that is case-insensitive and that normalizes whitespace violates the principle of least surprise, given that XML is case sensitive and that XPath 1.0 never normalized whitespace without explicit direction to do so.

**Comment by benibela** [comment]
I would expect it to have a definition in [2.1.1 Static Context](https://www.w3.org/TR/2014/REC-xpath-30-20140408/#static_context) where it introduces the default collation. But there it just says "A default initial value for each component must be specified by the host language. "

> If the default collation is not specified by the user or the system, 
  
but so it can be specified as a different one. Too bad it does not say how and where this specifiying could happen. Perhaps the W3C was thinking of XQuery when they wrote this sub-clause.


Then there follows the definition of the fn:compare function with two examples, where the default collation is not the codepoint collation

>given that XML is case-sensitive 


but I wrote everything only because I wanted to read some data from a HTML page

**Comment by kjhughes** [comment]
I hope you've found this feedback helpful.

Thank you for creating and providing your library and web interface.

**Comment by benibela** [comment]
I could also add an option where the user can choose another collation. But that would be redundant with collation declaration in XQuery.  For practical purposes there is no reason to choose XPath over XQuery. Other things have been busy this month
