### ISSUE TITLE
How to build all this?

### ISSUE THREAD

**Issue by OnkelTem** [benibela/xidel#35]
So `xidel` package is not in any Linux repository. At least it's missed in Ubnutu-breed.
Ok, let's build it. Unfortunately you didn't provide ANY instructions ANYWHERE on how to do this. 

I tried to run `build.sh` and `manage.sh` scripts but they just failed.

Specifically,  `build.sh` failes wih error: 

```
xidel.pas(33,6) Fatal: Can't find unit internetaccess used by xidel
```

while `manage.sh` cannot find some file which it assumes to be... outside of the repo:

```
./manage.sh: line 5: /home/user/src/xidel/../../../manageUtils.sh: No such file or directory
```

Would you please tell us how to do it?

**Comment by Reino17** [comment]
> Unfortunately you didn't provide ANY instructions ANYWHERE on how to do this.

That's not true.  
_http://videlibri.sourceforge.net/xidel.html#downloads:_
> The source history is stored in a [mercurial repository](https://sourceforge.net/p/videlibri/code/ci/tip/tree/) together with the VideLibri source and dependencies, licensed as GPLv3+. There are mirrors on [GitHub](https://github.com/benibela/xidel/), [Bitbucket](http://bitbucket.com/benibela/xidel) and [GitLab](https://gitlab.com/benito/xidel). These mirrors have the Xidel source only, in order to compile it you need to download the dependencies from their own repositories first. Or use the above source tarball, which also contains dependencies.
>
>The source then needs to be compiled with FreePascal.
In a Unix-like shell you compile it by calling `./build.sh`, which just calls FreePascal. If you want to FreePascal directly yourself, you can use `fpc xidel.pas` in which case you need to pass the paths to all directories of the source using the `-Fu`, `-Fi` options.
Alternatively, Xidel can be compiled using the Lazarus IDE. For this install `components/pascal/internettools.lpk` and `components/pascal/internettools_utf8.lpk` in Lazarus, then open `programs/internet/xidel/xidel.lpi` and click on Run\Compile.

This information however is not complete, because the [FLRE](https://github.com/benibela/flre) component is also needed.

This worked for me (to create a Windows binary):
```
$ hg clone http://hg.code.sf.net/p/videlibri/code videlibri-code

$ git clone https://github.com/benibela/flre.git videlibri-code/components/flre

$ ./videlibri-code/programs/internet/xidel/build.sh --compiler=/cygdrive/c/FPC-3.0.4/bin/i386-win32/fpc.exe
```

**Comment by OnkelTem** [comment]
It worked, beautiful! 
Thank you very much. 

> That's not true.
> http://videlibri.sourceforge.net/xidel.html#downloads:

Ah, now I see. So it was buried in the line of sight. 
Usually there's either a section called DEVELOPMENT or INSTALL in the README file or just a separate INSTALL file. I was looking for them.

**Comment by benibela** [comment]
I have added a section to the readme

**Comment by sebma** [comment]
> I have added a section to the readme

@benibela Great, can you please add a sentence in your README.md to explain how to run that [.travis.yml](../blob/master/.travis.yml) file on Linux ?

**Comment by benibela** [comment]
@sebma You do not run the .travis.yml file, you run the commands in it one by one. For example, line 17 has   `- mkdir import`, so you run  `mkdir import` : 


![grafik](https://user-images.githubusercontent.com/1205129/115990398-62386180-a5c3-11eb-849c-52a40a7c822b.png)
