### ISSUE TITLE
Allow escaping of quotes

### ISSUE THREAD

**Issue by Fuzzyma** [benibela/xidel#5]
I see myself often want to use something like this:

```bash
xidel foo.htm -e 'join(//something, "\",\""')
                                   --^^-^^--note these
```

Basically joining stuff together in csv format which requires quoted strings. However: xidel fails when using doublequotes there so the escaping does not work.
Is there a workaround or is there a chance that escaping gets added to xidel?

PS: Awesome tool!

**Comment by benibela** [comment]
It has escaping according to the XPath/XQuery standard ( https://www.w3.org/TR/xquery-31/#id-literals ):

Basically you need to write `""` rather than `\"`.

In XQuery mode you can also write `&quot;`



I was not sure which mode should be the default, so I made a [survey]( https://docs.google.com/forms/d/1GEzMSu1s595bzTCDzspc996xbzkcoOGqHABnHEsc5Zs)

In XPath/XQuery 3.1, which I have not yet implemented, there is an additional string type surrounded by :

     ``[ ]``
